### ISSUE TITLE
Support implicit build tools versions

### ISSUE THREAD

**Issue by koral--** [bitrise-steplib/steps-install-missing-android-tools#25]
Since (at least) Android Gradle Plugin 3.0.0-beta7 it has default and minimum supported build tools version. If version specified by `buildToolsVersion` in buildscript is lower, it is bumped to the minimum supported.

Here is the related warning message:
```
WARNING: The specified Android SDK Build Tools version (26.0.1) is ignored, as it is below the minimum supported version (26.0.2) for Android Gradle Plugin 3.0.0-beta7.
Android SDK Build Tools 26.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
```

Minimum version can be obtained via API: `com.android.builder.core.AndroidBuilder#MIN_BUILD_TOOLS_REV`

**Comment by viktorbenei** [comment]
Thanks @koral-- for the heads up!

Just a question, wouldn't this be solved by `yes | sdkmanager --licenses`?

Do you have a sample project we could reproduce the issue with?

**Comment by koral--** [comment]
Here is the project reproducing that warning: https://github.com/DroidsOnRoids/android-empty-library/tree/master/
And on the separate branch, there is another, new case - `buildToolsVersion` can be omitted, so default version taken from plugin will be used: https://github.com/DroidsOnRoids/android-empty-library/tree/build_tools_omitted

> wouldn't this be solved by `yes | sdkmanager --licenses`

After invoking that command, correct build tools version will be downloaded by a Gradle runner step (or something else which invokes Gradle), but not this one. This step however, will try to download build tools version which won't be used at all.

**Comment by viktorbenei** [comment]
If `yes | sdkmanager --licenses` does fix the issue then this should be fixed in the upcoming new version, where we will invoke `sdkmanager --licenses`, it's just work-in-progress right now, but should be released soon ;)

**Comment by trapacska** [comment]
Hey @koral-- !

Thank you for the report. The new version is out now: 
https://github.com/bitrise-steplib/steps-install-missing-android-tools/releases/tag/2.0.4

Closing the issue as it seems like it fixed the issue.
Please feel free to re-open this issue if you encounter any issues with it.

🎉🚀
