### ISSUE TITLE
Wrong plugin version mentioned in step description

### ISSUE THREAD

**Issue by vgaidarji** [bitrise-steplib/steps-install-missing-android-tools#29]
This step description has the wrong version mentioned in the description.
Please see the screenshot `If the Plugin version is 2.2.0 or later`, but the latest version at the moment is `2.0.5`.
![image](https://user-images.githubusercontent.com/3036347/32930360-fc635d4a-cb66-11e7-9668-4afbb6e213ee.png)

Is it intended and was added for future or just a typo?

**Comment by viktorbenei** [comment]
That "Plugin" version is for the Android Gradle plugin, not the step's version ;)

**Comment by viktorbenei** [comment]
This simply means that the step can auto detect whether android tools & gradle android plugin is up to date, in which case it can simply use `gradlew dependencies` or similar, in other case it falls back to a previous solution which parses things and installs them one by one (AFAIK).

**Comment by vgaidarji** [comment]
> That "Plugin" version is for the Android Gradle plugin, not the step's version ;)

Got it. But I find it very confusing.
Oh, wait. Bitrise operates with `steps` but not `plugins` 🤣 So it might not be that confusing though.

**Comment by kdobmayer** [comment]
Hi @vgaidarji 

Thanks for reporting the issue, we released a [new version](https://github.com/bitrise-steplib/steps-install-missing-android-tools/releases/tag/2.0.6) where the step description clarify that the mentioned version constraint is for `Android Plugin for Gradle` not the step itself.

**Comment by vgaidarji** [comment]
@kdobmayer that's very nice that you are pedantic in every aspect and paid attention to this "issues" as well. Thanks for that 👍 🤝

**Comment by viktorbenei** [comment]
Thanks for reporting @vgaidarji ! ;)
