### ISSUE TITLE
AndroidHome: parameter not specified - with bitrise cli

### ISSUE THREAD

**Issue by gaultierq** [bitrise-steplib/steps-install-missing-android-tools#33]
Running the step (2.1.0)
`- install-missing-android-tools: {}`
on my local machine, run into :
```
Configs:
- GradlewPath: android/gradlew
- AndroidHome:
Issue with input AndroidHome: parameter not specified
```
However, `echo $ANDROID_HOME` => `/Users/redacted/Library/Android/sdk`

Everything is fine when when CI

**Comment by viktorbenei** [comment]
Hi @gaultierq ,

Please make sure that `ANDROID_HOME` is set **before** you'd run the `bitrise run` command. 

Alternatively you can set it in Secrets locally, to have it defined. Probably this is the best solution, as Secrets should never be committed into the repo, and so those can be environment specific (it only exists on the host you define it).

If you'd have any questions just let us know! :)

**Comment by viktorbenei** [comment]
I'll close this issue here, but feel free to ask if you'd have any questions and we'll reopen it! :)

**Comment by prat3ik** [comment]
Hi @gaultierq 
Make sure you have selected Right Stack. If you have selected **XCode** then it would not find the 

> ANDROID_HOME

**Comment by kibotu** [comment]
I had a couple of submodules when I created a bitrise task, and for some reason bitrise failed to add the  `GRADLE_BUILD_FILE_PATH` and `GRADLEW_PATH` to the app environment and I got that error

here is how it probably should look like (at the end of your bitrise.yml file):

```
app:
  envs:
  - opts:
      is_expand: false
    GRADLE_BUILD_FILE_PATH: build.gradle
  - opts:
      is_expand: false
    GRADLEW_PATH: "./gradlew"
```

have a great day :)

**Comment by allan-simon** [comment]
I have ANDROID_HOME exported just before running and it still fails (locally)   , with 2.3.7

however if i set it  in the `envs` sections it works
