### ISSUE TITLE
Support Android P preview

### ISSUE THREAD

**Issue by tir38** [bitrise-steplib/steps-install-missing-android-tools#37]
We are starting to experiment with Android P preview and have a separate workflow to build a P version of our app. However we are getting this error as part of the `install-missing-android-tools` step

```
> Failed to find Platform SDK with path: platforms;android-P
```

**Comment by trapacska** [comment]
Hey @tir38 !

For now as I see the platform is not available from the sdkmanager yet.

```
$ANDROID_HOME/tools/bin/sdkmanager --list | grep "android-P"                                                                                                                               
  system-images;android-P;android-wear-cn;x86                                              | 2            | China version of Wear OS Intel x86 Atom System Image
  system-images;android-P;android-wear;x86                                                 | 2            | Wear OS Intel x86 Atom System Image
```

How did you get the P platform?

**Comment by tir38** [comment]
Interesting. That documentation you linked to must have changed since I initially setup P testing. The initial setup was to use:

```
targetSdkVersion = 'P'
compileSdkVersion = 'android-P'
```

not

```
targetSdkVersion = 28
compileSdkVersion = 28
```

I will re-try with 28 and see if it still fails.

**Comment by tir38** [comment]
Yep that looks like it fixed it. Thanks.
