### ISSUE TITLE
The SDK directory '/Users/***/Library/Android/sdk' does not exist.

### ISSUE THREAD

**Issue by fchristysen** [bitrise-steplib/steps-install-missing-android-tools#39]
I'm trying to run bitrise locally in docker. The step I use is `2.2.0`, and use this command `docker run --privileged --env CI=false --volume "$(pwd):/bitrise/src" --volume "/var/run/docker.sock:/var/run/docker.sock" --rm bitriseio/docker-android:latest bitrise run build-debug`.  The yml is run fine in bitrise machine. 
Why does it use my host machine path and not the one in docker?

Got this error 
```FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':accommodation'.
> The SDK directory '/Users/fchristysen/Library/Android/sdk' does not exist.

**Comment by godrei** [comment]
Hi, do you define the ANDROID_HOME env in your gradle files (mostly it is defined in the .gradle.properties file)? It seems in the container session the ANDROID_HOME env is set to your local machine's Android Home directory.

**Comment by fchristysen** [comment]
Hello, I've checked the `gradle.properties` and the ANDROID_HOME isn't there, also checked in the whole project, and found none. I only set the ANDROID_HOME env in my `~/.bash_profile` in my host machine.

**Comment by godrei** [comment]
Could you please try to temporary remove the `ANDROID_HOME` env in your bash profile and run a new build?

**Comment by viktorbenei** [comment]
@fchristysen can you please search for the path `/Users/fchristysen/Library/Android/sdk` in your android project? E.g. open it in Sublime Text or a similar text editor, and just search for this string (`/Users/fchristysen/Library/Android/sdk`).

**Comment by fchristysen** [comment]
@viktorbenei have search for it in the whole project and found none. 

@godrei have remove the `ANDROID_HOME` and `ANDROID_SDK_ROOT` (< also points to same path), but it still shows the same error. Also have confirm that those env vars are not set by echo-ing manually.

**Comment by godrei** [comment]
Could you please also search for `sdk.dir=` in your project?

**Comment by fchristysen** [comment]
The `sdk.dir=` is not found in the project

**Comment by viktorbenei** [comment]
@fchristysen please also search for `/Users/fchristysen` and `Library/Android/sdk`

It's defined somewhere in your project, as the docker command you copy pasted does not share anything else between the host and the guest, only the directory you run that command in and its subdirectories. So, it's defined somewhere in there - usually in the `local.properties` or similar file.

> have search for it in the whole project and found none.

Which tool did you use for the search if I might ask?

**Comment by fchristysen** [comment]
@viktorbenei I open the project using Visual studio code, and search with it (on the left menubar, second item from the top). Will try to search thoroughly.

**Comment by godrei** [comment]
Hi @fchristysen ,
i can confirm that AndroidStudio regenerates this file, we do not have an official recommendation for this situation for now. If it gets regenerated and you do not define manual properties there, you may delete this file in your workflow.

I'll close this issue, but if you need more info/help create a new issue on our discuss page: https://discuss.bitrise.io/c/issues!
