### ISSUE TITLE
Intermittent failures

### ISSUE THREAD

**Issue by scottkruse** [bitrise-steplib/steps-install-missing-android-tools#40]
install missing android tools is failing out with always latest set

**Comment by bitce** [comment]
Hi @scottkruse , 

Could you send us a build URL we could look into please?

**Comment by lewiemortier** [comment]
Experiencing the same issue here. Build URL: https://app.bitrise.io/build/8c4afb48a77bc15e

**Comment by scottkruse** [comment]
https://app.bitrise.io/build/340b3232507eb2fa

**Comment by bitce** [comment]
Hey guys, sorry for the delay here!

The step has been updated now, are you still experiencing the same issues on the latest version?

Also keep an eye out for the ongoing jcenter issue. We are recommending placing "google()" first in your build.gradle to bypass it.

**Comment by scottkruse** [comment]
So far so good! will report back if anything similar comes up

**Comment by godrei** [comment]
I'll close this issue, but if you need more info/help just open a new issue!
