### ISSUE TITLE
v2.3 fails to install ndk 17c

### ISSUE THREAD

**Issue by trevjonez** [bitrise-steplib/steps-install-missing-android-tools#43]
build url: `https://app.bitrise.io/build/de542474f443f26a`
stack: `android and docker on ubuntu 16.04` 
image: `bitriseio/android-ndk:v2018_10_06-06_38-b1205`

tar command is failing to unzip the ndk file. 

```
Failed to download NDK bundle, error: tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains ‘\305\v\\C7?x\226R3Fv’ where numeric off_t value expected
tar: Archive contains ‘G\177Q\223\336ba\222\236\312"\347’ where numeric off_t value expected
tar: A lone zero block at 1348922
tar: Exiting with failure status due to previous errors: exit status 2
```

**Comment by trapacska** [comment]
Hey @trevjonez !

You PR is merged and the new version is released: https://github.com/bitrise-steplib/steps-install-missing-android-tools/releases/tag/2.3.1

Thank you! 🚀
