### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

### ISSUE THREAD

**Issue by maxhille** [bitrise-steplib/steps-install-missing-android-tools#45]
We were out of nowhere encountering this error in one of our legacy apps CI  pipelines. Documenting my findings here to help others and I will also include a step-lib improvement suggestion.

After investigating a bit it seems (please correct me if I am wrong):
1. Bitrise recently updated the "default NDK version" to the recently[1] released version.
2. NDK r18 does not support android-gradle-plugin versions below 3.0.0 [1, all the way to the bottom]
3. Since our legacy app is still on some 2.x gradle-plugin version, we got the error

Obvious appraches to fix this:
1. Update the app to use newer build deps - not viable: that app will be replaced by a successor in the coming weeks and bumping the plugin opens a cascade of changes which we do not want to test etc.
2. Downgrade the NDK through the step-lib config: Does not work because of #43 and/or #44

Suggested step-lib improvements:
1. Fix the zipper #44
2. When NDK config "empty", actually delete the NDK folder.

Workaround:
I set the ANDROID_NDK_HOME env_var to "invalid_location". It seems that this will get rid of the "unwanted" r18 NDK

[1] https://github.com/android-ndk/ndk/wiki/Changelog-r18

**Comment by koral--** [comment]
Another option for your case may be to use LTS stack. NDK is not updated there.

**Comment by trapacska** [comment]
Hey there! Thank for reporting.

Since the version: https://github.com/bitrise-steplib/steps-install-missing-android-tools/releases/tag/2.3.0 there is a new input called `NDK Revision`, if you leave it as empty, it will unset the ANDROID_NDK_HOME env var.

Also #44 is merged and works like a charm. I am closing this issue now but feel free to re-open if you still encounter any issues with it!

Thanks! 🚀

**Comment by maxhille** [comment]
> Since the version: https://github.com/bitrise-steplib/steps-install-missing-android-tools/releases/tag/2.3.0 there is a new input called NDK Revision, if you leave it as empty, it will unset the ANDROID_NDK_HOME env var.

This did not help, I guess it does not remove the default (ie. latest) version from the SDK directory. That's why I had to set it to some nonexistent value via the env var.

**Comment by trapacska** [comment]
Sorry about that. Just fixed the issue, will be released very soon.

**Comment by trapacska** [comment]
Released! 🚀
