### ISSUE TITLE
Likely parsing bug when comment includes quotation marks in same line with versionName

### ISSUE THREAD

**Issue by ubuntudroid** [bitrise-steplib/steps-install-missing-android-tools#53]
There is a parsing issue when the "install-missing-android-tools" step scans a `build.gradle` file which contains a comment with quotation marks in the same line as `versionName` (probably also affects other properties expecting string (that is quoted) values, but didn't test). No problems when building the project locally.

The affected line looks something like the following:

```
versionName "0.1.0" // some comment with "quotation marks"
```

Removing the quotation marks from the comment fixes the issue.

Detailed error message looks like this:

```bash
Ensure required Android SDK components
Retrying...
Failed to ensure android components, error: output: FAILURE: Build failed with an exception.
* Where:
Build file '/bitrise/src/app/build.gradle' line: 14
* What went wrong:
Could not compile build file '/bitrise/src/app/build.gradle'.
> startup failed:
  build file '/bitrise/src/app/build.gradle': 14: unexpected token: as @ line 14, column 41.
     rsionName "0.1.2-61" workflow as well
                                   ^
  
  1 error
```

**Comment by ubuntudroid** [comment]
@bitce argh, had it in the clipboard, but forgot to paste it: https://app.bitrise.io/build/138fc2e1c5f558b1

**Comment by bitce** [comment]
Thanks! The team is on it, will get back to you once we have an update on the problem!

**Comment by trapacska** [comment]
Actually it was an issue with the step you used previously in your workflow. It changed your version incorrectly.

This release should fix this problem, please check and let us know if it is fixed: https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/releases/tag/1.2.0

Closing the issue, but feel free to re-open if the issue still persist.

🚀

**Comment by ubuntudroid** [comment]
@trapacska thanks a lot! 🙏
