### ISSUE TITLE
Is this step still required?

### ISSUE THREAD

**Issue by G00fY2** [bitrise-steplib/steps-install-missing-android-tools#58]
This is not really an issue, but more a general question (or maybe an improvement for the readme):

What exactly is the propose of this step? It starts a gradle task, scans the _app:dependency_ task output and tries to manually setup missing SDK components, right?  This sometimes takes 60-90 seconds.

What are the advantages when we already have: https://developer.android.com/studio/intro/update#download-with-gradle

The Android gradle plugin should already take care of all that: https://android.googlesource.com/platform/tools/base/+/refs/heads/studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/SdkHandler.java

As long as the licenses exist the plugin can automatically detect and install missing platform tools, platforms, buildTools, NDK, cmake and library requests.

Maybe we can skip the steps after `skdmanager --license` if Android plugin 2.2 or higher is found?

**Comment by koral--** [comment]
Look here: https://discuss.bitrise.io/t/removing-install-missing-android-tools-step/8439 and here https://bitrise.slack.com/archives/CESSAV1MM/p1558458638001400. 

There were discussions about this step and currently (6 months ago) it was stated that this step is still needed.

**Comment by G00fY2** [comment]
Hey @koral-- , thanks for the fast response!

Your answer on the discuss.bitrise.io thread confirms my assumption. Unfortunately I don't have access to the slack workspace. Maybe you can sum up the conversation, if there are any additional information?

To be completely safe you can probably just add a script step that runs `yes | sdkmanager --licenses >/dev/null`?


Maybe the Readme should point out, that this task is **not required** if the project uses a current Android Gradle Plugin and does not rely on older NDK versions?

A future improvement could be, to automatically detect the conditions when it is needed.

**Comment by koral--** [comment]
Here's @viktorbenei's message from slack which summarises everything:

> depends, really. if you have as much experience as @koral-- you can most likely resolve the issues the install missing android tools step meant to resolve automatically. if you’re less experienced or if you prefer the CI not breaking vs potentially slower builds then I’d suggest you to keep the step and instead report any performance issue to our support team via the onsite chat. We constantly work on improving the performance of our steps, but our priority is reliability and only after that performance - meaning we might include additional checks/things in our steps to ensure everything’s prepared, which can make things slower than if you wouldn’t check or do those things.
In short, if you want maximum performance even if you have to tweak things yourself/gain deeper knowledge about how things work we won’t stop you from removing that step/doing it the way that maximises  the build performance. In any other case and in general I’d suggest you to keep the step and instead report performance issues to our support, e.g. if you try the build without the step and it performs significantly faster send the two build URLs to support (one with and one without the step) so that they can inspect what causes the performance difference and improve the step(s).

**Comment by G00fY2** [comment]
Thanks.

Found out that the documentation already points out, that you do not have to rely on `Install missing Android SDK components` step: [Manual installation of Android SDKs](https://devcenter.bitrise.io/tips-and-tricks/android-tips-and-tricks/#manual-installation-of-android-sdks)
