### ISSUE TITLE
Install missing Android tools step succeeds but later license has not been accepted

### ISSUE THREAD

**Issue by bartonhammond** [bitrise-steplib/steps-install-missing-android-tools#6]
I added the **Install missing Android tools** step to my Android Workflow (https://www.bitrise.io/app/1e0425744dcc7ce3/workflow/editor) 

I added the Env Var `GRADLE_BUILD_FILE_PATH` to `./android/build.gradle`

The following is the step output:

```
+------------------------------------------------------------------------------+
| (2) install-missing-android-tools@0.9.2                                      |
+------------------------------------------------------------------------------+
| id: install-missing-android-tools                                            |
| version: 0.9.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-02-27T23:00:55Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[23:00:55] Start installing (golang) with apt-get       
INFO[23:00:55]  * [OK] Step dependency (go) installed, available. 

Configs:
- RootBuildGradleFile: ./android/build.gradle
- UpdateSupportLibraryAndPlayServices: true
- AndroidHome: /opt/android-sdk-linux

Search for root setting.gradle file
root build.gradle file: /bitrise/src/android/build.gradle
root settings.gradle file:: /bitrise/src/android/settings.gradle

Collect build.gradle files to analyze
active modules to analyze: [react-native-vector-icons]
build.gradle file not found for module: react-native-vector-icons at: /bitrise/src/android/react-native-vector-icons/build.gradle, error: %!s(<nil>)
build.gradle files to analyze: []

Collect dependencies to ensure

Ensure dependencies
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | install-missing-android-tools@0.9.2                           | 4.07 sec |
+---+---------------------------------------------------------------+----------+
```

Later I get this error:

```
wnload https://jcenter.bintray.com/com/google/guava/guava/18.0/guava-18.0.jar
File /root/.android/repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 23.0.1 in /opt/android-sdk-linux/licenses
Warning: License for package Android SDK Build-Tools 23.0.1 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 23.0.1].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 6.364 secs
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | gradlew (exit code: 1)                                        | 129 sec  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-script/issues             |
| Source: https://github.com/bitrise-io/steps-script                           |
+---+---------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment]
@godrei the key here is: `build.gradle file not found for module: `

IMO this step should keep analyzing the other files, as it doesn't fail (exit code != 0) anyway. Of course a warning should be printed, but keep analyzing.

Or does this log means that there was only one active module (`active modules to analyze: [react-native-vector-icons]`)?

**Comment by viktorbenei** [comment]
Ohh, and of course, thanks @bartonhammond for reporting! ;)

**Comment by godrei** [comment]
Hi @bartonhammond ,
sorry for my late response and thanks for the issue report!

Based on `install-missing-android-tools` log, it seems the step detects only one active model: `react-native-vector-icons` (which build.gradle file does not exists at the desired path).

But the `gradlew` steps builds the `app` module, based on that log, it seems the `app` is also an active module.

May i ask you to run: `tree ./ -L 3` command in your project root directory?

And could you please share with us, your `settings.gradle` file's content?

**Comment by shuse2** [comment]
Hello, I have the same issue, and my `settings.gradle` is like below.

```
rootProject.name = 'AwsomeApp'
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
include ':react-native-i18n'
project(':react-native-i18n').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-i18n/android')
include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/android/app/')

include ':app'
```

**Comment by viktorbenei** [comment]
@shuse2 thanks for the info! I'm sure this'll help others ;)

@godrei ping 👀

**Comment by godrei** [comment]
Hi @shuse2 and @bartonhammond ,
we released a new version ([2.0.0](https://github.com/bitrise-steplib/steps-install-missing-android-tools/releases/tag/2.0.0)) , which uses gradle commands to install the missing components, this version should fix your issue.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Comment by SeniorMobileDeveloper** [comment]
Hi @godrei ,
I added the **Install missing Android tools** step to my Android Workflow.
While running the step, I got this error.

`+------------------------------------------------------------------------------+

| (2) install-missing-android-tools@2.0.2                                      |
+------------------------------------------------------------------------------+
| id: install-missing-android-tools                                            |
| version: 2.0.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-10-04T08:51:59-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[08:51:59]  * [OK] Step dependency (go) installed, available. 
Configs:
- RootBuildGradleFile: android/build.gradle
- GradlewPath: android/gradlew
- AndroidHome: /Users/vagrant/Library/Android/sdk
Preparation
Set executable permission for gradlew
Ensure android licences
Initialize Android SDK
_Failed to create SDK manager, error: no sdk manager tool found at: /Users/vagrant/Library/Android/sdk/tools/android_
|                                                                              |
+---+---------------------------------------------------------------+----------+
| **x | install-missing-android-tools@2.0.2 (exit code: 1)**            | 3.71 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...bitrise-steplib/steps-install-missing-android-tools/issues |
| Source: ...://github.com/bitrise-steplib/steps-install-missing-android-tools |
+---+---------------------------------------------------------------+----------+`

It appears that my environment is missing android sdk. Can you please tell me how to install it?

**Comment by JUStrepsec** [comment]
C:\Users\bhushan>flutter doctor --android-licenses
Loading local repository...
[=========                              ] 25% Loading local repository...
[=========                              ] 25% Fetch remote repository...
[=========                              ] 25% Fetch remote repository...
[=============                          ] 34% Fetch remote repository...
[================                       ] 42% Fetch remote repository...
[================                       ] 42% Fetch remote repository...
[=================                      ] 44% Fetch remote repository...
[=================                      ] 45% Fetch remote repository...
[==================                     ] 46% Fetch remote repository...
[==================                     ] 47% Fetch remote repository...
[==================                     ] 48% Fetch remote repository...
[===================                    ] 48% Fetch remote repository...
[===================                    ] 49% Fetch remote repository...
[===================                    ] 50% Fetch remote repository...
[====================                   ] 51% Fetch remote repository...
[====================                   ] 52% Fetch remote repository...
[====================                   ] 53% Fetch remote repository...
[=====================                  ] 53% Fetch remote repository...
[=====================                  ] 54% Fetch remote repository...
[=====================                  ] 55% Fetch remote repository...
[======================                 ] 56% Fetch remote repository...
[======================                 ] 57% Fetch remote repository...
[=======================                ] 58% Fetch remote repository...
[=======================                ] 58% Fetch remote repository...

Warning: File C:\Users\bhushan\.android\repositories.cfg could not be loaded.
[=======================                ] 58% Fetch remote repository...
[=======================                ] 58% Computing updates...
[=============================          ] 75% Computing updates...
[=============================          ] 75% Computing updates...
[=======================================] 100% Computing updates...
All SDK package licenses accepted.
Anybody tell what is the problem

**Comment by viktorbenei** [comment]
Hi @JUStrepsec & @swmd - this issue is closed for a long time and is no longer tracked. Please create a new issue if you have a problem with this step.
