### ISSUE TITLE
Error: could not locate platform dir at ndk home: /opt/android-ndk

### ISSUE THREAD

**Issue by s7aycool** [bitrise-steplib/steps-install-missing-android-tools#64]
Hello. I am trying add NDK to step install-missing-android-tools@2.3.8 

1. In step settings I set ndk revision to r22-beta1 (also tried r22 - not available. Hasn't tried r21)
2. I launched build
3. I see error:
`Failed to download NDK bundle, error: could not locate platform dir at ndk home: /opt/android-ndk`

Build log:
https://app.bitrise.io/build/df6a03f97acea9c0#?tab=log

**Comment by s7aycool** [comment]
I set ndk revision to "21" and then build fails with `Caused by: org.gradle.api.InvalidUserDataException: NDK is not installed`

This can be temporarily fixed by setting ndk path in `local.properties` like this: `ndk.dir=/opt/var` but this is kinda deprecated

**Comment by chaitanyatanna-bitrise** [comment]
Hi @s7aycool 
May I ask what Android Gradle Plugin (AGP) version are you using in the project? Each AGP release is implicitly expecting a given NDK version, and if your Bitrise workflow installs the wrong NDK version that could produce an error like yours.

You have two options to sync NDK versions:
1. Explicitly declare the NDK version in build.gradle and configure the Bitrise step to download that version.
2. Rely on AGP choosing an NDK version and configure the Bitrise step to download that version. This might break your build in the future if AGP is upgraded, and you'll have to change the installed version on Bitrise too.

NDK versions have 2 formats, which makes configuration a bit confusing, but here's how they are mapped:
21.1.6352462 is r21b (first minor release of r21)
21.3.6528147 is r21d (fourth minor release of r21)

The Bitrise step uses the format 21a, 21b, 21c, etc. without the "r" prefix, so if you want to install the NDK version that AGP 4.1 is using (21.1.6352462) then you'll need to configure the Bitrise install step to download NDK version 21b.

Let me know if this helps.

Thanks
Chaitanya

**Comment by GrahamBorland** [comment]
I've recently been talking to Bitrise support about this. The NDK is extracted to the wrong path.

Let's say I want SDK revsion 21d, which maps to version 21.3.6528147.

This Bitrise step is installing the NDK to
```
/opt/android-ndk/android-ndk-r21d
```
and the `ANDROID_NDK_HOME` environment variable is being set to this path.

The build tools expect that `ANDROID_NDK_HOME` should contain the various NDKs, named according to their version (e.g. 21.3.6528147).

The build tools are looking for a directory named
```
$ANDROID_NDK_HOME/21.3.6528147/
```
but that path does not exist. The Bitrise step is extracting the specific NDK revision directly to `$ANDROID_NDK_HOME`, which is the wrong location.

**Comment by GrahamBorland** [comment]
FWIW I was able to resolve my problem by adding a script step to install the NDK using Android's SDK manager.
```
sdkmanager "ndk;21.3.6528147"
```

**Comment by s7aycool** [comment]
@GrahamBorland that means ndk will be downloaded every time? Maybe setting `ndk.dir=/opt/var` in `local.properties` on virtual machine would save some time

**Comment by ofalvai** [comment]
Hi there,

We are investigating why the NDK installation doesn't work on some projects while working on others. In the meantime, @GrahamBorland's workaround is reportedly working on the affected projects.

@s7aycool Once the NDK is downloaded using `sdkmanager` (and cached on Bitrise) it won't be downloaded in every run.

**Comment by s7aycool** [comment]
> We are investigating why the NDK installation doesn't work on some projects
Thanks! Waiting for the news

Btw `echo "ndk.dir=/opt/android-ndk/" >> local.properties` is working, too
