### ISSUE TITLE
Failed to find package 'platform;android-29'     

### ISSUE THREAD

**Issue by ODEVLAB** [bitrise-steplib/steps-install-missing-android-tools#72]
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_NG)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit
      https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
$ cmdline-tools/tools/bin/sdkmanager "platform;android-29" "build-tools;28.0.3" "extras;google;m2repository" "extras;android;m2repository"
Warning: Failed to find package 'platform;android-29'     

any help please

running Ubuntu 20.04 on my pc

**Comment by Roland-Bak** [comment]
Hello @ODEVLAB 👋
Could you please share the build URL and enable Support Access([https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/)), so that we may take a closer look? 🙂
