### ISSUE TITLE
NDK of image bitriseio/android-ndk-20.04 can't be used because ANDROID_NDK_HOME is unset when no revision is specified

### ISSUE THREAD

**Issue by AndreasBoehm** [bitrise-steplib/steps-install-missing-android-tools#77]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? **2.3.9**
- Is the issue reproducible with the latest version? **YES**
- Does the issue happen sporadically, or every time? **EVERY TIME**
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? **YES**

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

#### Actual
Using the image `bitriseio/android-ndk-20.04` in combination with this step results in the included NDK not being usable because ANDROID_NDK_HOME is getting cleared if i don't specify a NDK revision.
If I do specify a version (22) I am blocked by issue https://github.com/bitrise-steplib/steps-install-missing-android-tools/issues/74

#### Expected
ANDROID_NDK_HOME env-var should remain untouched when I don't specify a NDK revision.
Maybe a new toggle is required in the settings of the step `Use image-provided NDK revision'?

### Bitrise info

- Build URL: https://app.bitrise.io/build/785eb7fbcad9f9ea#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _**YES** / NO_
- Log: 

<details>
  <pre>
Clearing NDK environment
Unset ANDROID_NDK_HOME
  </pre>
</details>

### Steps to reproduce
1. Use docker-image `bitriseio/android-ndk-20.04` 
2. Use step `install-missing-android-tools` and do not specify a NDK revision

**Comment by ofalvai** [comment]
Hello @AndreasBoehm 👋 

Using the `ANDROID_NDK_HOME` has been deprecated on the Android Gradle Plugin side for a while and in version 4.1 it was removed completely in favor of defining the version in `build.gradle`. See this document for the details: https://github.com/android/ndk-samples/wiki/Configure-NDK-Path

We recommend upgrading your project to the latest Android Gradle Plugin version if it's possible. Furthermore, with the recent changes around NDK installation, we think it's better to run your workflows on our regular Docker image and use the step to install the required version at runtime.

**Comment by AndreasBoehm** [comment]
Helo @ofalvai,

thanks for your answer!

You are absolutely right, I mixed something up.

Sadly I can not use the regular Docker image and install the required version at runtime because of this bug: https://github.com/bitrise-steplib/steps-install-missing-android-tools/issues/74
