### ISSUE TITLE
Build Failed - install-missing-android-tools

### ISSUE THREAD

**Issue by Rajkumarrmani** [bitrise-steplib/steps-install-missing-android-tools#97]
In the Android Studio, this issue did not come. It works fine but here it shows the following error.

Run: failed to ensure android components, error: output: FAILURE: Build failed with an exception.
* Where:
Build file '/bitrise/src/app/build.gradle' line: 2
* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
      Your current JDK is located in /usr/lib/jvm/java-11-openjdk-amd64
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

**Comment by koral--** [comment]
You have to switch java to 17.
See: https://devcenter.bitrise.io/en/infrastructure/build-stacks/managing-java-versions.html#setting-java-version-with-the-set-java-version-step

**Comment by Rajkumarrmani** [comment]
It's worked fine as we expect. Thanks.
